/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;

    import laya.utils.ClassUtils;
	public class FunctemUI extends Box {
		public var textDesc:Text;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Box","props":{"y":0,"x":0,"width":200,"height":30},"compId":1,"child":[{"type":"Image","props":{"top":0,"skin":"ui/item/item_normal.png","right":0,"left":0,"bottom":0},"compId":26,"child":[{"type":"Image","props":{"skin":"ui/item/item_selected.png","name":"selectBox"},"compId":27},{"type":"Text","props":{"x":10,"width":180,"var":"textDesc","valign":"middle","text":"项目名称","height":30,"color":"#ffffff","align":"center","runtime":"laya.display.Text"},"compId":28}]}],"loadList":["ui/item/item_normal.png","ui/item/item_selected.png"],"loadList3D":[]};
		public function FunctemUI(){
		createUI(uiView);
		}
		private function createUI(uiData:Object):void
		{
			ClassUtils.createByJson(uiData, this, this);

		}

	}
}