/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;
	import script.view.ControlPanel;

	public class ControlPanelUI extends Scene {
		public var listFunc:List;
		public var btnToggle:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/ControlPanel");

		}

	}
}